[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true

[ui]
hideSidebarNav = true
hideTopBar = true

[app]
target = "main.py"
